package com.rodrigmatrix.sigaaufc.firebase

const val VISUALIZOU_ONBOARDING = "INICIOU_ONBOARDING"
const val FINALIZOU_ONBOARDING = "FINALIZOU_ONBOARDING"
const val ERRO_ONBOARDING = "ERRO_ONBOARDING"


const val NOTIFICAR_TESTE = "TOCOU_NOTIFICACAO_TESTE"


const val NOTIFICACAO_ARQUIVO = "NOTIFICOU_ARQUIVO"
const val NOTIFICACAO_NOTA = "NOTIFICOU_NOTA"
const val NOTIFICACAO_NOTICIA = "NOTIFICOU_NOTICIA"

const val COMPRAR_APP = "TOCOU_COMPRAR"
const val DESATIVAR_ANUNCIOS = "TOCOU_DESATIVAR_ANUNCIOS"

const val LOGIN_BUTTON = "TOCOU_BOTAO_LOGIN"
const val PROFILE_BUTTON = "TOCOU_IMAGEM_PERFIL"